apps/beltreview/urls.py
from django.conf.urls import url
from . import views
# from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index),
    url(r'^register$', views.register),
    url(r'^books$', views.books),
    url(r'^logout$', views.logout),
    url(r'^login$', views.login),
    url(r'^addbook$', views.addbook),
    url(r'^add$', views.add),
    url(r'^bookprofile/(?P<id>\d+)$', views.bookprofile),
    url(r'^addreview$', views.addreview),
    url(r'^userprofile/(?P<id>\d+)$', views.userprofile),




]

review/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.beltreview.urls')),
]

apps/beltreview/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def register(self, name, alias, email, password, conpass):
        errors = []
        the_user = User.objects.filter(email = email)
        if len(name) < 1:
            errors.append('Name is too short')
        if len(alias) < 1:
            errors.append('Alias is too short')
        if not EMAIL_REGEX.match(email):
            errors.append('Invalid Email')
        if the_user:
            errors.append('Already in system')
        if len(password) < 5:
            errors.append('Name is too short')
        if conpass != password:
            errors.append('Passwords don\'t match')
        if len(errors) > 0:
            return errors
        else:
            return True

    def login(self, email, password):
        errors = []
        the_user = User.objects.filter(email = email)
        if the_user:
            if bcrypt.hashpw(password.encode('utf-8'), the_user[0].password.encode('utf-8')) == the_user[0].password:
                #needed help from other assignment
                return True
            else:
                errors.append('Wrong Email or Password')
                return errors
        else:
            errors.append('Wrong Email or Password')
            return errors


class User(models.Model):
    name = models.CharField(max_length = 200)
    alias = models.CharField(max_length = 200)
    email = models.CharField(max_length = 200)
    password = models.CharField(max_length = 200)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

class Book(models.Model):
    book = models.CharField(max_length = 200)
    author = models.CharField(max_length = 200, default = '')


class Review(models.Model):
    book = models.ForeignKey(Book)
    name = models.ForeignKey(User)
    rating = models.IntegerField(default = 0)
    review = models.TextField(max_length = 1000)

apps/beltreview/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User, UserManager, Book, Review
from django.db.models import Count
import bcrypt

def index(request):
    return render(request, 'beltreview/index.html')

def register(request):
    name = request.POST['name']
    alias = request.POST['alias']
    email = request.POST['email']
    password = request.POST['password']
    conpass = request.POST['conpass']
    check = User.objects.register(name, alias, email, password, conpass)
    if check == True:
        pwhash = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
        user = User.objects.create(name = name, alias = alias, email = email, password = pwhash)
        request.session['current_user'] = user.id
        return redirect ('/books')
    else:
        for i in range(0, len(check)):
            messages.warning(request, check[i])
        return redirect ('/')

def books(request): #illustrating to the user the books
    user = User.objects.get(id = request.session['current_user'])
    first_three = Book.objects.all()[0:3]
    book = Book.objects.all()[3:]
    context = {'user': user, 'books': book, 'first_three':first_three}
    return render(request, 'beltreview/books.html', context)

def login(request):
    email = request.POST['email']
    password = request.POST['password']
    check = User.objects.login(email, password)
    if check == True:
        user = User.objects.get(email = email)
        request.session['current_user'] = user.id
        return redirect('/books')
    else:
        messages.warning(request, check[0])
        return redirect('/')

def logout(request):
    request.session['current_user'] = 0
    return redirect('/')

def add(request):
    user = User.objects.get(id = request.session['current_user'])
    author = Book.objects.values('author').annotate(count = Count('author'))#annotate groups an author with multiple books using the count
    context = {'users':user, 'authors':author}
    return render(request, 'beltreview/add.html', context)

def addbook(request):
    user = User.objects.get(id = request.session['current_user'])
    book = request.POST['book']
    if len(request.POST['oldauthor']) > 0:
        author = request.POST['oldauthor']
    else:
        author = request.POST['newauthor']
    rating = request.POST['rating']
    review = request.POST['review']
    new_book = Book.objects.create(book = book, author = author)
    Review.objects.create(book = new_book, name = user,rating = rating, review = review)
    book_id = new_book.id
    return redirect('/bookprofile/%s' % book_id) #linking redirect with ID

def bookprofile(request, id):
    book = Book.objects.get(id = id)
    context = {'books': book}
    return render(request, 'beltreview/bookprofile.html', context)

def addreview(request):
    book = Book.objects.get(id = request.POST['book'])
    user = User.objects.get(id = request.session['current_user'])
    rating = request.POST['rating']
    review = request.POST['review']
    Review.objects.create(book = book, name = user,rating = rating, review = review)
    return redirect('/bookprofile/%s' % book.id)

def userprofile(request, id):
    user = User.objects.get(id = id)
    books = []
    user_count = Review.objects.filter(name = user).annotate(count = Count('review'))
    user_review = Review.objects.annotate(count = Count('review')).filter(name = user).values('book')
    for b in user_review:
        the_book = Book.objects.get(id = b['book'])
        books.append(the_book.book)
    non_repeating = []
    for a in range(0, len(books)):
        if a+1<len(books) and books[a] != books[a+1]:
            book = Book.objects.get(book = books[a])
            non_repeating.append({'name':books[a], 'id': book.id})
    book = Book.objects.get(book = books[len(books)-1])
    non_repeating.append({'name':books[len(books)-1], 'id': book.id})
    context = {'user':user, 'user_count':user_count, 'user_review':user_review, 'all': non_repeating}
    return render(request, 'beltreview/user.html', context)

apps/beltreview/templates/beltreview/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Book and Review</title>
  </head>
  <body>
    <h1>Add a New Book Title and a Review</h1>
    <a href="/books">Home</a>
    <a href="/logout">Log Out</a>
    <form action="/addbook" method="post">
      {% csrf_token %}
    Book Title: <input type="text" name="book"><br>
    Author: <select name="oldauthor">
          <option></option>
          {% for author in authors %}
            <option>{{author.author}}</option>
          {% endfor %}
            </select>
            <input type="text" name="newauthor"><br>
    Review: <textarea name="review"></textarea><br>
    Rating: <select name="rating">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>
        <button type="submit">Add Book and Review</button>
    </form>
  </body>
</html>

apps/beltreview/templates/beltreview/bookprofile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Book Profile</title>
  </head>
  <body>
    <h1>{{books.book}}</h1>
    <h3>Author: {{books.author}}</h3>
    <a href="/books">Home</a>
    <a href="/logout">Log Out</a>

    <br>
    <h1>Reviews</h1>

    {% for review in books.review_set.all %}
    <hr>
    <ul>
      <li>Rating: {{review.rating}} / 5</li>
      <li><a href="/userprofile/{{review.name.id}}">{{review.name.name}}</a> says:{{review.review}}</li>
    </ul>
    {% endfor %}
    <h4>Add a Review:</h4>
    <form action="/addreview" method="post">
       {% csrf_token %}
       <input type="hidden" name="book" value="{{books.id}}">
      <textarea name="review"></textarea>
      Rating: <select name="rating">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
              <button type="submit">Submit Review</button>

    </form>

  </body>
</html>

apps/beltreview/templates/beltreview/books.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Books</title>
    <style media="screen">
      .rest{
        width: 200px;
        height: 70px;
        overflow-y: scroll;
      }
    </style>
  </head>
  <body>
    <h1>Welcome {{user.name}}!</h1>
    <a href="/logout">Log Out</a>
    <a href="/add">Add Book and Review</a>
    <h3>Recent Book Reviews:</h3>
    {% for book in first_three %}
    <ul>
      <li><a href="/bookprofile/{{book.id}}">{{book.book}}</a></li>
      <li>Rating: {{book.review_set.all.0.rating}} / 5</li>
      <li><a href="/userprofile/{{book.review_set.all.0.name.id}}">{{book.review_set.all.0.name.name}}</a> says: {{book.review_set.all.0.review}}</li>
    </ul>
    {% endfor %}

    <h3>Other Books with Review</h3>
    <div class="rest">

    <ul>

    {% for book in books %}
    <li><a href="/bookprofile/{{book.id}}">{{book.book}}</a></li>
    {% endfor %}
  </ul>
</div>
  </body>
</html>

apps/beltreview/templates/beltreview/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Belt Review</title>
  </head>
  <body>
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    <fieldset>
      <legend>Register</legend>
      <form action="/register" method="post">
        {% csrf_token %}
      Name: <input type="text" name="name"><br>
      Alias: <input type="text" name="alias"><br>
      Email: <input type="text" name="email"><br>
      Password <input type="text" name="password"><br>
      *Password should be at least 5 characters<br>
      Conform PW: <input type="text" name="conpass"><br>
      <button type="submit">Register</button>
      </form>
    </fieldset>
    <fieldset>
        <legend>Login</legend>
        <form action="/login" method="post">
          {% csrf_token %}
        Email: <input type="text" name="email"><br>
        Password: <input type="text" name="password"><br>
        <button type="submit">Login</button>
      </form>
    </fieldset>
  </body>
</html>

apps/beltreview/templates/beltreview/user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User</title>
  </head>
  <body>
    <h3>User Alias: {{user.alias}}</h3>
    <a href="/books">Home</a>
    <a href="/logout">Log Out</a>
    <a href="/add">Add Book and Review</a>
    <h5>Name: {{user.name}}</h5>
    <h5>Email: {{user.email}}</h5>
    <h5>Total Reviews: {{user_count.count}}</h5>
    <h5>Posted Reviews on the following books:</h5>
    <ul>
      {% for review in all %}
      <li><a href="/bookprofile/{{review.id}}">{{review.name}}</a></li>
      {% endfor %}
    </ul>
  </body>
</html>